apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark
resources:
  - config.yaml
configMapGenerator:
  - name: ctgov-job-args
    literals:
      - SOURCE_PATH="s3a://km-bonn-prod-nfdi4health-etl-data/ctgov/2025-09-15-test"
