apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac/config.yaml

namespace: spark

configMapGenerator:
  - name: etl-job-s3-config
    literals:
      - AWS_ENDPOINT_URL="" # TODO: Insert S3 endpoint URL. Example: https://s3.de-west-1.psmanaged.com

secretGenerator:
  - name: etl-job-s3-credentials
    literals:
      - AWS_ACCESS_KEY_ID="" # TODO: Insert S3 access key ID.
      - AWS_SECRET_ACCESS_KEY="" # TODO: Insert S3 secret access key.